### PR TITLE
#169 Fix autosuggest error

### PR DESCRIPTION
**Pull request by georgehelman**

### CODE REVIEW

**Comment by robert-w-gries** [comment]
Is there a behavior change with this? Does clicking on an auto suggestion now remove focus on the input box and prevent you from typing until you re-click it?

**Comment by robert-w-gries** [comment]
I also think my PR here fixes the issue #266

**Review by copelco — APPROVED** [review]
Works for me

**Comment by robert-w-gries** [comment]
#266 should have fixed this issue. Closing for now and will re-open if the issue comes up again

**Pull request closed without merging**
